### ISSUE TITLE
libmuse jar in the sampleApp?

### ISSUE THREAD

**Issue by jdpigeon** [padster/Muse-EEG-Toolkit#1]
I got the app to build, but I had to copy paste the libs folder with the libmuse jar from eegToolKit to sampleApp because there wasn't one there

shouldn't there be a libs dir there? I can make a PR of course

**Comment by padster** [comment]
Good point, thanks - I excluded the built jars from github, but will add it back with a release folder of the built library jar to make it easier to download.

**Comment by padster** [comment]
Actually, sorry, I see what you're saying now. I also don't have the libmuse.jar in sampleApp's lib/ folder, so I'm confused why it was working for me at all...

I cleaned up the build files in https://github.com/padster/Muse-EEG-Toolkit/commit/54245ca37e1a8bf3fe069343779bf82f585a23e0 - libmuse is not longer specifically mentioned.

also, sampleApp lists project(':eegtoolkit') as a dependency, so libmuse should get pulled in through that; hopefully that also fixes it.

**Comment by jdpigeon** [comment]
I'll give it a shot with a fresh clone. Good work on the app!

**Comment by jdpigeon** [comment]
Installing sample app works from a fresh clone now!
